name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
      - run: npm install
      - run: |
          moon update
          moon install
          mkdir -p target/web
          cp -R web/* target/web/
          moon build --target js
          cp target/js/release/build/main/main.js target/web/main.js
          npm install npx
          npx tailwindcss -i web/styles.css -o target/web/styles.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/web
