name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stable-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            path: ubuntu_x86_64_moon_setup

    runs-on: ${{ matrix.os.name }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon test
        run: |
          moon update
          moon install
          moon test --target js --serial --release
          moon test --target js --serial

      - name: moon check
        run: moon check --target js --deny-warn

      - name: moon info
        run: |
          moon info --target js
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
